language: node_js
node_js:
- 6
branches:
  only:
  - master
before_script:
- npm install
script: ls -al post_f7f8d692395949d76b5d.md
after_success: npm run deploy
env: 
  global:
      - QIITA_POST_ID: f7f8d692395949d76b5d
      - QIITA_POST_TITLE: "Qiita投稿テスト"
      - secure: NVXMrZ+TTzZX0fhnR22D4xGhbLJ93JLN9N2kSsk954RERNWDtUxorXg/9Cj5WFJTniOsaX6PzyDHtHMGKTNF7nNcYsfZWg8ztLg/J3ZMCljjZcGuCIpXLnkBx8Ew80LvVlQpB8mUkLzNxC8d7sahDIl78umh7Qd+Nw9uaiaQbLFND1LTV6Dm0SXhiY67BeokM2i1+TLUBT7Hvjzpy5tCa2EueGIQLJ66twLAg/RyIR298s+r/Ob2OgQf/0qbdiYXGjCK0wgFLmZ6xNz/NlWT0jJuBJk4x5aZ4iDM3rTg91Qm0yMKB1bvXIYOwcLJo2Ku0k4i00evc4UONNvcffxdqXc40GABBCXqXiaA+oAWy+GuYHZIeDchbhIrHg36kwGRt4pcrm6L9QNVhsHoS4CMtokYoz1mHxeCiqsFhoAN2Kb6/TD5wBuYe5+d9ZpykvedR2J56oXHq085gx4Zli7pNV6cqkn+UDzLdYaUmhluXHu5We7wTVEWrxgiyXcmKY+zCv3+GFOuvClI4EyOoJAod3Nljq/vjy2rx/wu2aGbglmEP0fupyvfxArw5F6avW7fYwkQzkw86TndSScNz7co2TzPztH6cAVX6YiPjp8IT5cqmJ5dKeHeU7Sk3OcFYobEDPFSC9jYGfAA7gwiB1zfFarndFpcuyzBLzTpli7Dd6U=
