language: node_js
node_js:
- 6
branches:
  only:
  - master
before_script:
- npm install
script: ls -al post_f7f8d692395949d76b5d.md
after_success: npm run deploy
env:
  global:
  - QIITA_POST_ID: f7f8d692395949d76b5d
  - QIITA_POST_TITLE: "Qiita投稿テスト"
  - secure: Zp8szFqpUmQgevLNi4G7MWgxvWiSiHnclDm53sFjF7c20ok0m7SJu6qghUjJ1iWLjLkcITwres5U8ViAam7OhQazUJ/B8hd/vuOIPDCl8/picGQrKULXblGSPHnSUYSuzoRDfVFdg/1YNg3qh36mNfyjt9Vpd/dooWJ9qlzOeIZUVvHPhQ89mYkUj3oIvtcBX+02U07HfOevtvnG8TcDyNAPiOpjCSJ2r55YkdL/u7izLl4bo64+IrDl7kMJFu2CmGsz2eAzTQWZQT7YQqEaCkw3tU2/OptbFA0EmaxxyG0WaE0Ke3g8pmeL4fyPi00bLVCMOwHTExX4uNw4gHeN1vrT4bwIdEiQWs430Ij+MOB1sThB67eUa8aEVF/ovlgm3/08QacLv+OgThLYKXVzwql8yqCQrT50qM9nVV3c/TDExs51917PCYfWuy01oWpPPoAo29hKD16xW+/cbi88HdIT1/rQ+BeRP7UzlcZHY2fVGnH1Ox19baIYgH0uyGImoFhdVHUUmpqTmSKnYi0xWPbro4OkGRqFb9iW5H15yzGY5cxdZ2ulJAFd+Oo0uD5h8tpRlvjdlPSvGwuqN4VEGtTcd7ZeZFff/PtUAX3jDNdwVQomxc/Nu3U30j2ZgxoH5bBB97HNvLq/FWPWWRM6vIBuHxGNeZvB5xmuaAxAT/0=
