language: node_js
node_js:
- 6
branches:
  only:
  - master
before_script:
- npm install
script: ls -al post_f7f8d692395949d76b5d.md
after_success: npm run deploy
env:
  global:
  - QIITA_POST_ID: f7f8d692395949d76b5d
  - QIITA_POST_TITLE: "Qiita投稿テスト"
  - secure: gKD2cJNu9h82vWNk17sAVyl4KiyRo0MP0jPZ4Nq+bgKeWLg7NYyLY/CGbV50FZdp7sfZkcPPy9qkEXcZvIUXYhLjYE9LRk+PE8eRJusrao2+yl4ud3nuHm7ELxt0kjk9HiVDPfEPhMGrHqmXN44bZodmNRVTfh/oMwNMQIzCj9XLfkFMbD9+XunoPX4zRAS0A/DVInhALhhCwfbIoj3XiygFgMl6ucfmW7tb9hfhPonxkjQB5m5jLb7BhfFwz8u/3bQ2iq08wR7Pg8SXy9dX88YvL/x4RsnvPMHPKisCABRjrz85XO2fJBK9YoLRVkVWNG9ffIUVa6Q2q0JQ9+iiGLz4H1psl+11gMCER0Qav7UdglvYaAz0swjDUQ4IdPrIyYtTbqKQlHqitqkj8PVtgjRCKcQHbPKPy/asIYvIjuqERNFQE8puV87/ADydPgUgX5eoDcLt4Ko27TikHzJenQLhtTsU+EwxYcukBhrcXXm7s2Fn7PskFaYNH0aHyjZ27oDD2IalgyL2zsZXXw3PX97AmngFBYK3+/nvVOWcWi2Q1AMGhLKywc1RvFQII4dqdUkaklz/Qrqgxu3926ltESIrxAFdBPymspM57zDjqpY36rYrJ62GFgZking/91FotSqZCSXrQxxQ0ftnecyUE3/HLbe3Nh0h5G0jCKrcuVc=
